version: '3'

volumes:
    project_postgres_data:
        driver: local
    minio_data:
        driver: local
    imgproxy_data:
        driver: local

services:
    project:
        image: project
        build:
            context: ..
            dockerfile: ../Dockerfile
        env_file:
            - dev.env
        ports:
            - 8080:8080
        restart: unless-stopped
        depends_on:
            - sample_project_postgres

    sample_project_postgres:
        image: postgres:9-alpine
        env_file:
            - dev.env
        ports:
            - 5432:5432
        healthcheck:
            test: pg_isready
            interval: 1m30s
            timeout: 10s
            retries: 3
        volumes:
            - sample_project_postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    minio:
        image: minio/minio:RELEASE.2021-03-04T00-53-13Z
        volumes:
            - minio_data:/mnt/data1
        expose:
            - "9000"
        ports:
            - 9000:9000
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minio123
        #    command: server http://minio{1...4}/data{1...2}
        command: server /mnt/data1
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3

    imgproxy:
        image: darthsim/imgproxy:latest
        #    volumes:
        #      - imgproxy_data:/path/to/project/images
        ports:
            - 9080:8080
        environment:
            #      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/path/to/project/images
            - IMGPROXY_USE_S3=true
            - AWS_ACCESS_KEY_ID=minio
            - AWS_SECRET_ACCESS_KEY=minio123
            - IMGPROXY_QUALITY=50
            #      - IMGPROXY_KEY
            #      - IMGPROXY_SALT
            - IMGPROXY_S3_REGION=us-east-2
            #      - IMGPROXY_S3_ENDPOINT=s3://%bucket_name/%file_key
            #      - IMGPROXY_S3_ENDPOINT=s3://%bucket_name/%file_key?%version_id
            - IMGPROXY_S3_ENDPOINT=http://minio:9000
        healthcheck:
            test: [ "CMD", "imgproxy", "health" ]
            timeout: 10s
            interval: 10s
            retries: 3
        restart: unless-stopped
