version: '3'

volumes:
    sample_project_imgproxy_data:
        driver: local

services:
    imgproxy:
        image: darthsim/imgproxy:latest
        container_name: sample_project_imgproxy
        #    volumes:
        #      - imgproxy_data:/path/to/project/images
        ports:
            - 9080:8080
        environment:
            #      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/path/to/project/images
            - IMGPROXY_USE_S3=true
            - AWS_ACCESS_KEY_ID=minio
            - AWS_SECRET_ACCESS_KEY=minio123
            - IMGPROXY_QUALITY=50
            #      - IMGPROXY_KEY
            #      - IMGPROXY_SALT
            - IMGPROXY_S3_REGION=us-east-2
            #      - IMGPROXY_S3_ENDPOINT=s3://%bucket_name/%file_key
            #      - IMGPROXY_S3_ENDPOINT=s3://%bucket_name/%file_key?%version_id
            - IMGPROXY_S3_ENDPOINT=http://minio:9000
        healthcheck:
            test: [ "CMD", "imgproxy", "health" ]
            timeout: 10s
            interval: 10s
            retries: 3
        restart: unless-stopped
