version: '3'

volumes:
    sample_project_postgres_data:
        driver: local


services:
    sample_project_postgres:
        image: postgres:16-alpine
        container_name: sample_project_postgres
        env_file:
            - dev.env
        ports:
            - 5432:5432
        healthcheck:
            test: pg_isready
            interval: 1m30s
            timeout: 10s
            retries: 3
        volumes:
            - sample_project_postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

